#!/usr/bin/env python3
"""One-off ingest of footwear sheets into the picgen library. Usage: ingest_footwear.py <folder with sheet PNGs>"""
import importlib.util, os, pathlib, json, sys
spec = importlib.util.spec_from_file_location("app", pathlib.Path(__file__).resolve().parent.parent / "app.py"); app = importlib.util.module_from_spec(spec); spec.loader.exec_module(app)
IMG = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else os.environ.get("FOOTWEAR_SRC", "footwear"))
SK = ("skip", None)
# (sheet, grid, caption, top, [(label, keywords) per row of 3 views])
SHEETS = [
 (37, "3x2", 0.2, 0.03, [("flip-flop", ["flip flop", "flip flops", "flipflop", "flipflops", "thong sandal", "thong sandals", "!flip"]),
                         ("slide sandal", ["slide sandal", "slide sandals", "pool slide", "pool slides", "shower slides", "!slide"])]),
 (38, "3x2", 0.2, 0.03, [("sport sandal", ["sport sandal", "sport sandals", "sports sandal", "sports sandals", "hiking sandal", "hiking sandals", "tevas", "chacos", "outdoor sandals"]),
                         ("huarache sandal", ["huarache", "huaraches", "huarache sandal", "woven leather sandal", "woven sandal", "woven sandals"])]),
 (39, "3x2", 0.2, 0.12, [("gladiator sandal", ["gladiator sandal", "gladiator sandals", "gladiators", "roman sandal", "roman sandals"]),
                         ("cork footbed sandal", ["cork footbed sandal", "cork sandal", "cork sandals", "birkenstock", "birkenstocks", "birks", "two strap sandal", "two-strap sandals", "buckle sandal", "buckle sandals"])]),
 (40, "3x2", 0.2, 0.03, [("fisherman sandal", ["fisherman sandal", "fisherman sandals", "closed toe sandal", "closed-toe sandal", "closed toe sandals"]),
                         ("wooden clog", ["wooden clog", "wooden clogs", "wood clog", "wood clogs", "dutch clog", "dutch clogs", "swedish clog", "swedish clogs", "!clog", "!clogs"])]),
 (41, "3x2", 0.22, 0.03, [("green low-top canvas sneaker", ["low top canvas sneaker", "low-top canvas sneaker", "low top sneaker", "low-top sneaker", "low tops", "low-tops", "canvas sneaker", "canvas sneakers", "canvas shoes", "converse", "chucks", "chuck taylors", "green sneaker", "green sneakers", "!sneaker", "!sneakers", "!trainers"]),
                          ("khaki high-top canvas sneaker", ["high top canvas sneaker", "high-top canvas sneaker", "high top sneaker", "high-top sneaker", "high tops", "high-tops", "hi tops", "hi-tops", "khaki sneaker", "khaki sneakers", "!sneaker", "!sneakers"])]),
 (42, "3x2", 0.2, 0.03, [("running shoe", ["running shoe", "running shoes", "runners", "jogging shoes", "athletic shoes", "gym shoes", "!trainers", "!sneaker", "!sneakers"]),
                         ("dad sneaker", ["dad sneaker", "dad sneakers", "dad shoes", "chunky sneaker", "chunky sneakers", "chunky trainers", "triple s", "!sneaker", "!sneakers"])]),
 (43, "3x2", 0.2, 0.03, [("skate shoe", ["skate shoe", "skate shoes", "skater shoes", "skateboarding shoes", "vans", "old skool", "!sneaker", "!sneakers"]),
                         ("slip-on sneaker", ["slip on sneaker", "slip-on sneaker", "slip on sneakers", "slip-ons", "slip ons", "slip on shoes", "laceless sneakers", "!sneaker", "!sneakers"])]),
 (44, "3x2", 0.25, 0.03, [("basketball high-top", ["basketball high top", "basketball high-top", "basketball shoe", "basketball shoes", "basketball sneakers", "jordans", "air jordan", "air jordans", "red and white high tops", "!sneaker", "!sneakers"]),
                          ("retro leather trainer", ["retro leather trainer", "retro trainer", "retro trainers", "leather trainer", "leather trainers", "tennis shoes", "tennis shoe", "white leather sneakers", "retro sneakers", "sambas", "gazelles", "!sneaker", "!sneakers", "!trainers"])]),
 (45, "3x3", 0.03, 0.03, [("tan leather work boot", ["leather work boot", "leather work boots", "work boot", "work boots", "timberlands", "timbs", "tan work boots", "construction boots", "lace-up work boots", "!boot", "!boots"]), SK, SK]),
 (45, "3x3", 0.2, 0.03, [SK, SK, ("hiking boot", ["hiking boot", "hiking boots", "hiking shoes", "trail boots", "trekking boots", "mountain boots", "merrells", "!boot", "!boots"])]),
 (46, "auto", 0.2, 0.03, [("chelsea boot", ["chelsea boot", "chelsea boots", "chelseas", "elastic sided boots", "elastic-sided boots", "!boot", "!boots"]), SK,
                         ("cowboy boot", ["cowboy boot", "cowboy boots", "western boot", "western boots", "cowgirl boots", "ropers", "!boot", "!boots"])]),
 (47, "3x2", 0.2, 0.03, [("combat boot", ["combat boot", "combat boots", "military boots", "army boots", "tactical boots", "doc martens", "dr martens", "docs", "!boot", "!boots"]),
                         ("rain boot", ["rain boot", "rain boots", "rubber boots", "wellies", "wellington boots", "wellingtons", "gumboots", "galoshes", "!boot", "!boots"])]),
 (48, "3x2", 0.2, 0.03, [("chukka boot", ["chukka boot", "chukka boots", "chukkas", "desert boot", "desert boots", "!boot", "!boots"]),
                         ("snow boot", ["snow boot", "snow boots", "winter boot", "winter boots", "insulated boots", "sorels", "pac boots", "!boot", "!boots"])]),
 (49, "3x2", 0.28, 0.03, [("oxford dress shoe", ["oxford dress shoe", "oxford dress shoes", "oxford shoe", "oxford shoes", "oxfords", "dress shoe", "dress shoes", "formal shoes", "!shoes"]),
                         ("derby shoe", ["derby shoe", "derby shoes", "derbies", "derbys", "blucher", "bluchers", "!shoes"])]),
 (50, "3x2", 0.2, 0.03, [("penny loafer", ["penny loafer", "penny loafers", "loafer", "loafers"]),
                         ("wingtip brogue", ["wingtip brogue", "wingtip brogues", "wingtip", "wingtips", "brogue", "brogues", "wing tip shoes", "wing tips"])]),
 (51, "3x3", 0.2, 0.03, [("monk strap shoe", ["monk strap shoe", "monk strap shoes", "monk strap", "monk straps", "monkstrap", "monkstraps", "buckle dress shoes"]),
                         ("boat shoe", ["boat shoe", "boat shoes", "deck shoe", "deck shoes", "topsiders", "top-siders", "sperrys", "sperry"]), SK]),
 (52, "auto", 0.24, 0.03, [SK, ("patent leather tuxedo shoe", ["patent leather tuxedo shoe", "tuxedo shoe", "tuxedo shoes", "patent leather shoes", "patent shoes", "patent leather dress shoes", "opera shoes", "black tie shoes", "formal black shoes"]),
                           SK, ("leather moccasin", ["leather moccasin", "leather moccasins", "moccasin", "moccasins", "mocs", "driving moccasins", "driving shoes", "driving loafers"])]),
 (53, "3x3", 0.08, 0.03, [("black classic pump", ["classic pump", "classic pumps", "high heel pump", "high heel pumps", "high heels", "high heel", "black pumps", "black heels", "court shoes", "court shoe", "!pump", "!pumps", "!heel", "!heels"]), SK, SK]),
 (53, "3x3", 0.2, 0.03, [SK, SK, ("red stiletto", ["stiletto", "stilettos", "stiletto heels", "stiletto heel", "red heels", "red high heels", "red stilettos", "!heel", "!heels"])]),
 (54, "3x2", 0.2, 0.03, [("black kitten heel", ["kitten heel", "kitten heels", "low heels", "low heel pumps", "!heel", "!heels"]),
                         ("black wedge sandal", ["wedge sandal", "wedge sandals", "wedges", "wedge heels", "wedge heel", "platform wedge sandals", "!wedge"])]),
 (55, "3x2", 0.2, 0.03, [("platform heel", ["platform heel", "platform heels", "platform pumps", "platform pump", "platform high heels", "!platform", "!heel", "!heels"]),
                         ("pink ballet flat", ["ballet flat", "ballet flats", "ballerina flats", "ballerinas", "ballet shoes", "pink flats", "flat shoes", "!flat", "!flats"])]),
 (56, "3x2", 0.2, 0.03, [("strappy heeled sandal", ["heeled sandal", "heeled sandals", "heel sandal", "heel sandals", "strappy heels", "strappy sandals", "block heel sandals", "block heels", "dress sandals", "evening sandals", "!heel", "!heels"]),
                         ("knee-high boot", ["knee high boot", "knee-high boot", "knee high boots", "knee-high boots", "knee boots", "tall boots", "riding boots", "!boot", "!boots"])]),
 (57, "3x2", 0.2, 0.03, [("ankle bootie", ["ankle bootie", "ankle booties", "ankle boot", "ankle boots", "heeled ankle boots", "bootie", "booties", "!boot", "!boots"]),
                         ("over-the-knee boot", ["over the knee boot", "over-the-knee boot", "over the knee boots", "over-the-knee boots", "thigh high boots", "thigh-high boots", "otk boots", "!boot", "!boots"])]),
 (58, "3x2", 0.2, 0.03, [("mary jane shoe", ["mary jane", "mary janes", "mary jane shoe", "mary jane shoes", "maryjane", "maryjanes", "strap flats", "school shoes"]),
                         ("espadrille wedge", ["espadrille wedge", "espadrille wedges", "wedge espadrilles", "espadrille sandals", "rope wedge", "rope wedges", "!wedge", "!espadrille", "!espadrilles"])]),
 (59, "3x3", 0.2, 0.03, [("block heel mule", ["mule", "mules", "block heel mule", "block heel mules", "heeled mules", "slide heels", "backless heels", "open toe mules"]), SK,
                         ("navy pointed flat", ["pointed flat", "pointed flats", "pointed toe flat", "pointed toe flats", "pointed-toe flats", "navy flats", "flat shoes", "ballet flats", "!flat", "!flats"])]),
 (60, "3x2", 0.2, 0.03, [("chunky platform sneaker", ["platform sneaker", "platform sneakers", "chunky platform sneaker", "platform shoes", "platform trainers", "!platform", "!sneaker", "!sneakers"]),
                         ("slingback heel", ["slingback", "slingbacks", "slingback heel", "slingback heels", "slingback pumps", "sling back heels", "sling backs", "!heel", "!heels"])]),
 (61, "3x3", 0.2, 0.03, [("brown foam clog", ["foam clog", "foam clogs", "crocs", "croc", "rubber clogs", "garden clogs", "!clog", "!clogs"]),
                         ("green house slipper", ["house slipper", "house slippers", "slipper", "slippers", "bedroom slippers", "indoor slippers", "scuffs"]), SK]),
 (62, "3x2", 0.2, 0.03, [("fringe moccasin slipper", ["moccasin slipper", "moccasin slippers", "fringe moccasin", "fringe moccasins", "fringed moccasins", "minnetonka", "!moccasin", "!moccasins", "!slipper", "!slippers"]),
                         ("canvas espadrille", ["espadrille", "espadrilles", "canvas espadrille", "canvas espadrilles", "rope sole shoes", "jute sole shoes"])]),
 (63, "3x2", 0.2, 0.03, [("water shoe", ["water shoe", "water shoes", "aqua shoes", "aqua socks", "swim shoes", "reef shoes", "beach shoes"]),
                         ("soccer cleat", ["soccer cleat", "soccer cleats", "football boots", "football boot", "soccer boots", "soccer shoes", "cleats", "cleat", "studs"])]),
 (64, "3x3", 0.2, 0.03, [("grey cycling shoe", ["cycling shoe", "cycling shoes", "bike shoes", "biking shoes", "clipless shoes", "spd shoes", "road cycling shoes"]),
                         ("wrestling shoe", ["wrestling shoe", "wrestling shoes", "wrestling boots", "boxing boots", "boxing shoes", "mat shoes"]), SK]),
 (65, "3x2", 0.2, 0.03, [("teal low-top canvas sneaker", ["teal low top sneaker", "teal low-top sneaker", "teal canvas sneaker", "teal canvas sneakers", "teal sneakers", "teal shoes", "!sneaker", "!sneakers"]),
                         ("teal high-top canvas sneaker", ["teal high top sneaker", "teal high-top sneaker", "teal high tops", "teal high-tops", "!sneaker", "!sneakers"])]),
 (66, "3x2", 0.2, 0.03, [("brown leather work boot", ["brown work boot", "brown work boots", "brown leather boots", "brown lace up boots", "lace-up boots", "lace up boots", "!boot", "!boots"]),
                         ("tan hiking boot", ["tan hiking boot", "tan hiking boots", "brown hiking boots", "leather hiking boots", "!boot", "!boots"])]),
 (67, "3x2", 0.2, 0.03, [("tan chelsea boot", ["tan chelsea boot", "tan chelsea boots", "light brown chelsea boots", "suede chelsea boots", "!boot", "!boots"]),
                         ("tan cowboy boot", ["tan cowboy boot", "tan cowboy boots", "light brown cowboy boots", "embroidered cowboy boots", "!boot", "!boots"])]),
 (68, "3x2", 0.2, 0.03, [("tan monk strap shoe", ["tan monk strap", "tan monk straps", "light brown monk strap", "single monk strap"]),
                         ("tan boat shoe", ["tan boat shoe", "tan boat shoes", "light brown boat shoes", "leather boat shoes"])]),
 (69, "3x2", 0.2, 0.03, [("black patent derby shoe", ["black patent shoes", "black patent derby", "patent derby", "shiny black dress shoes", "black dress shoes", "black formal shoes", "!shoes"]),
                         ("tan leather moccasin", ["tan moccasin", "tan moccasins", "tan leather moccasin", "tan leather moccasins", "tan driving shoes", "!moccasin", "!moccasins"])]),
 (70, "3x2", 0.2, 0.03, [("green classic pump", ["green pumps", "green pump", "green heels", "green high heels", "emerald heels", "emerald pumps", "!pump", "!pumps", "!heel", "!heels"]),
                         ("green stiletto", ["green stiletto", "green stilettos", "green stiletto heels", "emerald stilettos", "!heel", "!heels"])]),
 (71, "3x2", 0.2, 0.03, [("black patent kitten heel", ["patent kitten heel", "patent kitten heels", "black patent heels", "kitten heels with bow", "bow heels", "!heel", "!heels"]),
                         ("tan wedge sandal", ["tan wedge sandal", "tan wedge sandals", "tan wedges", "cork wedge sandals", "cork wedges", "brown wedges", "!wedge"])]),
 (72, "3x2", 0.2, 0.03, [("backless loafer mule", ["backless mule", "backless mules", "loafer mule", "loafer mules", "backless loafer", "backless loafers", "slip on loafer", "slip on loafers", "!mule", "!mules", "!loafer", "!loafers"]),
                         ("red pointed-toe flat", ["red flats", "red flat shoes", "red pointed flats", "red pointed-toe flats", "pointed toe flat", "pointed-toe flat", "!flat", "!flats"])]),
 (73, "3x2", 0.2, 0.03, [("tan foam clog", ["tan foam clog", "tan foam clogs", "tan crocs", "beige crocs", "khaki crocs", "!crocs", "!clog", "!clogs"]),
                         ("tan house slipper", ["tan house slipper", "tan house slippers", "tan slippers", "beige slippers", "!slipper", "!slippers"])]),
 (74, "3x3", 0.2, 0.03, [("green cycling shoe", ["green cycling shoe", "green cycling shoes", "green bike shoes", "!cycling"]),
                         ("brown wrestling shoe", ["brown wrestling shoe", "brown wrestling shoes", "brown wrestling boots", "!wrestling"]), SK]),
 (75, "3x2", 0.2, 0.03, [("teal cycling shoe", ["teal cycling shoe", "teal cycling shoes", "teal bike shoes", "neon cycling shoes", "yellow and teal cycling shoes"]),
                         ("black wrestling shoe", ["black wrestling shoe", "black wrestling shoes", "black wrestling boots", "black boxing boots"])]),
]
total = 0
for n, grid, cap, top, rows in SHEETS:
    data = (IMG / f"{n}.png").read_bytes()
    labels = [r[0] for r in rows]; kws = [r[1] for r in rows]
    added = app.add_library([data], labels, "footwear", "", grid, cap, 3, top, kws)
    total += len(added)
    print(n, grid, "->", [a["tag"] for a in added])
print("TOTAL footwear items:", total)
